# Site
repository: taabroeders/code
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tommy Broeders
title: PhD Student
email: t.broeders@amsterdamumc.nl
website: www.github.com/taabroeders

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: BroedersTommy
github_username:  taabroeders
# stackoverflow_username: xx
# dribbble_username: xx
# facebook_username: xx
# flickr_username: xx
# instagram_username: xx
linkedin_username: tommy-broeders-561253109
# xing_username: x
# pinterest_username: x
# youtube_username: x
# googleplus_username: x
orcid_username: 0000-0003-2884-2827

# Additional icon links
additional_links:
- title: Publications
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Tommy-Broeders-2/publications
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tommy and I'm a PhD student at the department of Anatomy and Neurosciences (Amsterdam UMC, location VUmc). I am a <mark>computational neuroscientist</mark> and my research focuses on <mark>brain network dynamics</mark> across diseases and disorders (primarily multiple sclerosis).

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: List of publications
        link: https://pubmed.ncbi.nlm.nih.gov/?term=%22broeders+ta*%22%5Bauthor%5D&sort=date
        link_text: All Publications
        additional_links:
          - title:  Dorsal attention network centrality increases during recovery from acute stress exposure
            icon: fas fa-book
            url: https://doi.org/10.1016/j.nicl.2021.102721
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
	  Dorsal attention network centrality increases during recovery from acute stress exposure
        description: | # this will include new lines to allow paragraphs
          Stress is a major risk factor for the development of almost all psychiatric disorders. In addition to the acute stress response, an efficient recovery in the aftermath of stress is important for optimal resilience. Increased stress vulnerability across psychiatric disorders may therefore be related to altered trajectories during the recovery phase following stress. Such recovery trajectories can be quantified by changes in functional brain networks. This study therefore evaluated longitudinal functional network changes related to stress in healthy individuals (N = 80), individuals at risk for psychiatric disorders (healthy siblings of schizophrenia patients) (N = 39), and euthymic bipolar I disorder (BD) patients (N = 36). Network changes were evaluated before and at 20 and 90 min after onset of an experimental acute stress task (Trier Social Stress Test) or a control condition. Whole-brain functional networks were analyzed using eigenvector centrality as a proxy for network importance, centrality change over time was related to the acute stress response and recovery for each group. In healthy individuals, centrality of the dorsal attention network (DAN; p = 0.007) changed over time in relation to stress. More specifically, DAN centrality increased during the recovery phase after acute stress exposure (p = 0.020), while no DAN centrality change was observed during the initial stress response (p = 0.626). Such increasing DAN centrality during stress recovery was also found in healthy siblings (p = 0.016), but not in BD patients (p = 0.554). This study highlights that temporally complex and precise changes in network configuration are vital to understand the response to and recovery from stress.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amsterdam UMC, location VUmc
        link: https://anatomy-neurosciences.com
        link_text: anatomy-neurosciences.com
        sub_title: PhD Student
        caption: May 2020 - Present
        quote: >
          Network Resilience
        description: | # this will include new lines to allow paragraphs
            Quentifying network resilience by looking at brain network dynamics across diseases and disorders.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Utrecht University
        caption: 2017 - 2019
        sub_title: MSc Neuroscience and Cognition
        quote: >
          Neuroscience and Cognition
        description: | # this will include new lines to allow paragraphs
          Bioinformatics Profile

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in brain networks some of my other interests and hobbies are:
      - Climbing
      - Gaming (rocket league)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
