# Site
repository: taabroeders/code
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tommy Broeders
title: PhD Student
email: t.broeders@amsterdamumc.nl
#website: www.github.com/taabroeders

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: BroedersTommy
github_username:  taabroeders
# stackoverflow_username: xx
# dribbble_username: xx
# facebook_username: xx
# flickr_username: xx
# instagram_username: xx
linkedin_username: tommy-broeders-561253109
# xing_username: x
# pinterest_username: x
# youtube_username: x
# googleplus_username: x
orcid_username: 0000-0003-2884-2827

# Additional icon links
additional_links:
- title: Researchgate
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Tommy-Broeders-2/publications
- title: PubMed Publications
  icon: fas fa-book
  url: https://pubmed.ncbi.nlm.nih.gov/?term=%22broeders+ta*%22%5Bauthor%5D&sort=date

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: G-6PKMWB3LPN #"UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tommy and I'm a PhD student at the department of Anatomy and Neurosciences (Amsterdam UMC, location VUmc). I am a <mark>computational neuroscientist</mark> and my research focuses on <mark>brain network dynamics</mark> across diseases and disorders (primarily multiple sclerosis).

  This page is mainly intended to provide a quick overview of my shared code. Feel free to contact me if you are interested in applying any code to your own research!

content:
  - title: Shared Code
    layout: list
    content:
      - layout: left
        title: Generate surrogate data
        caption: <mark>MATLAB</mark>
        link: https://github.com/taabroeders/Recon_Dyn_MS/blob/main/Generate_surrogate.m
        link_text: Go to code
        description: |
          This code will perform phase randomization on fourier transformed data, consistently across timeseries. This preserves static connectivity and n-lag autocorrelation, but time-dependent connectivity properties are randomized. 
      - layout: left
        title: Community Detection
        caption: <mark>MATLAB</mark>
        link: https://github.com/taabroeders/Recon_Dyn_MS/blob/main/CommunityDetection.m
        link_text: Go to code
        description: |
          This code will perform community detection for multilayer connectivity matrices. The code is relatively computationally inexpensive and uses prior information on subnetwork organization to initialize/constrain the detection. 

  - title: Research experience
    layout: text

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        link_text: View all publications
        link: https://pubmed.ncbi.nlm.nih.gov/?term=%22broeders+ta*%22%5Bauthor%5D&sort=date
      - layout: center
        title: "First-authored publications:"
      - layout: left
        title: Brain Communications
        sub_title: 2022
        link: https://doi.org/10.1093/braincomms/fcac095
        link_text: Go to article
        description: | # this will include new lines to allow paragraphs
          ##  **"A more unstable resting-state functional network in cognitively declining multiple sclerosis"**
      - layout: left
        title: Journal of Pyschopharmacology
        sub_title: 2022
        link: https://doi.org/10.1177/02698811221077199
        link_text: Go to article
        description: | # this will include new lines to allow paragraphs
          ##  **"Glutamate levels across deep brain structures in patients with a psychotic disorder and its relation to cognitive functioning"**
      - layout: left
        title: Neuroimage Clinical
        sub_title: 2020
        link: https://doi.org/10.1016/j.nicl.2021.102721
        link_text: Go to article
        description: | # this will include new lines to allow paragraphs
          ## **"Dorsal attention network centrality increases during recovery from acute stress exposure"**

  - title: Positions # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amsterdam UMC, location VUmc
        link: https://anatomy-neurosciences.com
        link_text: anatomy-neurosciences.com
        sub_title: PhD Student
        caption: May 2020 - Present
        description: | # this will include new lines to allow paragraphs
          ## **Quentifying network resilience by looking at brain network dynamics across diseases and disorders**
      - layout: left
        title: Amsterdam UMC, location VUmc
        # link: https://anatomy-neurosciences.com
        # link_text: anatomy-neurosciences.com
        sub_title: Research Assistant
        caption: Jan 2019 - May 2020
        description: | # this will include new lines to allow paragraphs
          ## **Functional connectivity in neurological and psychiatric disorders**
      - layout: left
        title: Amsterdam UMC, location VUmc
        # link: https://anatomy-neurosciences.com
        # link_text: anatomy-neurosciences.com
        sub_title: Research Intern
        caption: Okt 2018 - Jan 2019
        description: | # this will include new lines to allow paragraphs
          ## **Functional connectivity changes in the brain during acute stress recovery.**
      - layout: left
        title: UMC Utrecht
        # link: https://anatomy-neurosciences.com
        # link_text: anatomy-neurosciences.com
        sub_title: Research Intern
        caption: Nov 2017 - Sep 2018
        description: | # this will include new lines to allow paragraphs
          ## **Functional connectivity changes in the brain during acute stress recovery.**

  -  title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Utrecht University
        caption: 2017 - 2019
        sub_title: MSc Neuroscience and Cognition
        description: | # this will include new lines to allow paragraphs
          ## **Neuroscience and Cognition**
       #  quote: >
       #    Bioinformatics profile
      - layout: left
        title: Tilburg University
        caption: 2014 - 2017
        sub_title: BSc Psychology
        description: | # this will include new lines to allow paragraphs
          ## **Psychology**
        # quote: >
        #   Exchange to Trent University (Canada)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
